name: photo_uploader
description: "A new Flutter project for uploading photos to the cloud."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  crypto: ^3.0.6
  dropdown_button2: ^2.3.9
  file_picker: ^10.3.2
  firebase_auth: ^5.7.0
  firebase_core: ^3.15.2
  flutter:
    sdk: flutter
  flutter_datetime_picker_plus: ^2.2.0
  flutter_dotenv: ^5.2.1
  flutter_overlay_window: ^0.4.5
  flutter_secure_storage: ^9.2.4
  flutter_web_auth_2: ^4.0.0
  get: ^4.7.2
  google_fonts: ^6.3.0
  google_sign_in: ^6.3.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.2.1
  image: ^4.5.4
  path: ^1.9.0
  watcher: ^1.1.3
  get_storage: ^2.1.1
  logger: ^2.0.2+1
  connectivity_plus: ^5.0.2
  permission_handler: ^11.4.0
  equatable: ^2.0.5
  appwrite: ^18.0.0
  network_info_plus: ^5.0.3
  ftpconnect: ^2.0.7
  shared_preferences: ^2.2.2
  google_generative_ai: ^0.4.3
  camera: ^0.10.5+9
  sensors_plus: ^4.0.2
  device_info_plus: ^11.5.0
  exif: ^3.3.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  intl: ^0.19.0

dev_dependencies:
  dependency_validator: ^4.1.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
  build_runner: ^2.5.4
  test: ^1.25.15

flutter:
  uses-material-design: true
  assets:
    - lib/.env