name: photo_uploader
description: "A new Flutter project for uploading photos to the cloud."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  crypto: ^3.0.6
  dropdown_button2: ^2.3.9
  file_picker: ^10.3.2
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_datetime_picker_plus: ^2.2.0
  flutter_dotenv: ^6.0.0
  flutter_overlay_window: ^0.5.0
  flutter_secure_storage: ^9.2.4
  flutter_web_auth_2: ^4.0.0
  get: ^4.7.2
  google_fonts: ^6.3.0
  google_sign_in: ^7.1.1
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  http: ^1.2.1
  image: ^4.5.4
  path: ^1.9.0
  watcher: ^1.1.3
  get_storage: ^2.1.1
  logger: ^2.0.2+1
  connectivity_plus: ^6.1.5
  permission_handler: ^12.0.1
  equatable: ^2.0.5
  appwrite: ^18.0.0
  network_info_plus: ^6.1.4
  path_provider: ^2.1.1
  ftpconnect: ^2.0.7
  shared_preferences: ^2.2.2
  google_generative_ai: ^0.4.3
  camera: ^0.11.2
  sensors_plus: ^6.1.2
  device_info_plus: ^11.5.0
  exif: ^3.3.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  intl: ^0.20.2

dev_dependencies:
  dependency_validator: ^5.0.2
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/.env