name: photo_uploader
description: "A new Flutter project for uploading photos to the cloud."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  crypto: ^3.0.3
  dropdown_button2: ^2.3.9
  file_picker: ^8.0.3
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  flutter:
    sdk: flutter
  flutter_datetime_picker_plus: ^2.2.0
  flutter_dotenv: ^5.1.0
  flutter_overlay_window: ^0.4.4
  flutter_secure_storage: ^9.2.2
  flutter_web_auth_2: ^3.1.2
  get: ^4.6.6
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  googleapis: ^13.1.0
  http: ^1.2.1
  image: ^4.2.0
  path: ^1.9.0
  provider: ^6.1.2
  watcher: ^1.1.0

dev_dependencies:
  dependency_validator: ^4.1.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/.env
