// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMRip6Oiz-sePJb5xbivlKjMQerwkJn2w',
    appId: '1:424570474094:web:e509b6976ae0b09962607f',
    messagingSenderId: '424570474094',
    projectId: 'izza-films',
    authDomain: 'izza-films.firebaseapp.com',
    storageBucket: 'izza-films.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3DGNk1HGmgm6tfmCVZR_rl0PrpcmEM24',
    appId: '1:424570474094:android:2947d343acbd495962607f',
    messagingSenderId: '424570474094',
    projectId: 'izza-films',
    storageBucket: 'izza-films.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4mkf1P_hJlN6fdxLKDd9epRKKF8MdMEc',
    appId: '1:424570474094:ios:2342fdd0e6b9d20662607f',
    messagingSenderId: '424570474094',
    projectId: 'izza-films',
    storageBucket: 'izza-films.appspot.com',
    iosBundleId: 'com.example.photoUploader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4mkf1P_hJlN6fdxLKDd9epRKKF8MdMEc',
    appId: '1:424570474094:ios:2342fdd0e6b9d20662607f',
    messagingSenderId: '424570474094',
    projectId: 'izza-films',
    storageBucket: 'izza-films.appspot.com',
    iosBundleId: 'com.example.photoUploader',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMRip6Oiz-sePJb5xbivlKjMQerwkJn2w',
    appId: '1:424570474094:web:074cf02eac4314c962607f',
    messagingSenderId: '424570474094',
    projectId: 'izza-films',
    authDomain: 'izza-films.firebaseapp.com',
    storageBucket: 'izza-films.appspot.com',
  );
}
